config/routes.rb
Rails.application.routes.draw do
  root 'solutions#index'

  resources :solutions, shallow: true do
    member do
      get 'preview'
    end

    resources :scenarios, except: [:index]
    resources :resources, only: [:new, :create, :edit, :update, :destroy]
  end

  #
  # TODO - How else to avoid deeply nested routes without re-generating
  #        these Scenarios resources? Passing an empty array to only
  #        ensures that no new resources are generated as we've already
  #        generated everything we need above (with solutions/scenarios)
  #
  resources :scenarios, only: [] do
    resources :products, only: [:search, :create, :destroy]
  end

  post '/products/search', to: 'products#search', as: :products_search

  devise_for :users
end

app/views/resources/_form.html.erb
<%= form_for object, remote: true do |f| %>
  <div class="<%= container_class %>">
    <%= f.label :body %>
    <%= f.text_field :body %>

    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <% if new? %>
    <%= f.submit 'save', class: 'btn primary', id: 'save_resource' %>
  <% elsif edit? %>
    <div class="card_admin">
      <%= f.submit 'save', class: 'link primary', id: 'save_resource' %>
    </div>
  <% end %>
<% end %>

app/views/resources/_resource.html.erb
<%= div_for resource, class: 'card' do %>
  <div class="card_container">
    <%= content_tag :p, resource.body %>

    <%= content_tag :small do %>
      <%= link_to resource.url %>
    <% end %>
  </div>

  <div class="card_admin">
    <%= link_to 'edit', edit_resource_path(resource), remote: true, class: 'link plain' %>
    <%= link_to 'delete', resource_path(resource), method: :delete, remote: true, class: 'link delete delete_resource' %>
  </div>
<% end %>

app/views/resources/_resources.html.erb
<header class="collection-header">
  <%= content_tag :h2, 'Resources', class: 'collection-type' %>
  <%= link_to 'new resource', '#', class: 'btn secondary show-new-resource', id: 'show_new_resource' %>
</header>

<% if @page.resources.each do |resource| %>
<section class="resource card">
  <div class="card-container">
    <%= content_tag :p, resource.body %>

    <%= content_tag :small do %>
      <%= link_to resource.url %>
    <% end %>
  </div>

  <div class="card-admin">
    <%= link_to 'edit', edit_resource_path(resource), class: 'link plain' %>
    <%= link_to 'delete', resource_path(resource), method: :delete, remote: true, class: 'link plain delete-resource' %>
  </div>
</section>
<% end.empty? %>
  <section class="empty">
    <p>no saved resources&#133;</p>
  </section>
<% end %>

app/views/resources/create.js.erb
<%= render 'shared/create', object: @resource %>

app/views/resources/destroy.js.erb
<%= render 'shared/destroy', object: @resource %>

app/views/resources/edit.js.erb
<%= render 'shared/edit', resource: 'resource', object: @resource %>

app/views/resources/new.js.erb
<%= render 'shared/new', resource: 'resource', object: [@solution, @solution.resources.build] %>

app/views/resources/update.js.erb
<%= render 'shared/update', object: @resource %>