config/routes.rb
Rails.application.routes.draw do
  root 'solutions#index'

  resources :solutions, shallow: true do
    member do
      get 'preview'
    end

    resources :scenarios, except: [:index]
    resources :resources, only: [:new, :create, :edit, :update, :destroy]
  end

  #
  # TODO - How else to avoid deeply nested routes without re-generating
  #        these Scenarios resources? Passing an empty array to only
  #        ensures that no new resources are generated as we've already
  #        generated everything we need above (with solutions/scenarios)
  #
  resources :scenarios, only: [] do
    resources :products, only: [:search, :create, :destroy]
  end

  post '/products/search', to: 'products#search', as: :products_search

  devise_for :users
end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  extend FriendlyId

  belongs_to :solution
  has_many :products

  validates_presence_of :name

  # Use :name field as slug for ID
  friendly_id :name, use: :slugged

  # Paperclip file configuration
  has_attached_file :avatar,
                    :styles => { :default => '175x175' },
                    :default_url => '/assets/images/defaults/avatar.png'

  # Paperclip validation helper method to ensure header image type is valid
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  respond_to :js

  before_action :authenticate_user!
  before_action :set_solution, only: [:new, :create]
  before_action :set_scenario, only: [:edit, :update, :destroy]

  def new
    @scenario = Scenario.new
  end

  def create
    @scenario = @solution.scenarios.create(scenario_params)
  end

  def edit
  end

  def update
    @scenario.update(scenario_params)
  end

  def destroy
    @scenario.destroy
  end

  private

  def scenario_params
    params.require(:scenario).permit(:name, :quote, :pitch, :avatar, :solution_id)
  end

  def set_solution
    @solution = Solution.friendly.find(params[:solution_id])
  end

  def set_scenario
    @scenario = Scenario.friendly.find(params[:id])
  end
end

app/views/scenarios/_form.html.erb
<%= form_for object, remote: true, html: { multipart: true } do |f| %>
  <div class="<%= container_class %>">
    <ul class="errors"></ul>

    <% if edit? %>
      <%= image_tag @scenario.avatar, class: 'icon' %>
    <% end %>

    <%= f.label :name, 'Scenario Name' %>
    <%= f.text_field :name, class: 'instance_name' %>

    <%= f.label :quote %>
    <%= f.text_field :quote, autofocus: true %>

    <%= f.label :pitch %>
    <%= f.text_field :pitch %>

    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>

  <% if new? %>
    <%= f.submit 'save', class: 'btn primary', id: 'save_scenario' %>
  <% elsif edit? %>
    <div class="card_admin">
      <%= f.submit 'save', class: 'link primary', id: 'save_scenario' %>
    </div>
  <% end %>
<% end %>

app/views/scenarios/_index.html.erb
<section class="scenario card" id="scenario-<%= object.id %>" data-name="<%= object.name.parameterize %>">
  <div class="card-container">
    <%= image_tag object.avatar, class: 'scenario-avatar icon' %>
    <%= content_tag :h2, object.name %>
    <%= content_tag :h3, object.quote %>
    <%= content_tag :p , object.pitch %>

    <section class="products">
      <%= content_tag :h4, 'Products' %>
      <% if object.products.each do |product| %>
        <%= render 'products/index', object: product %>
      <% end.empty? %>
        <%= render 'products/empty' %>
      <% end %>
    </section>
  </div>

  <div class="card-admin">
    <%= button_tag 'add products', class: 'link primary js-modal-toggle', data: { name: object.name.parameterize } %>
    <%= link_to 'edit', edit_scenario_path(object), remote: true, class: 'link plain' %>
    <%= link_to 'delete', scenario_path(object), method: :delete, remote: true, class: 'link plain delete-scenario' %>
  </div>
</section>

app/views/scenarios/_new_form.html.erb
<%= form_for [object, object.scenarios.build], remote: true, html: { multipart: true } do |f| %>
  <%= render 'form_fields', f: f %>
<% end %>

app/views/scenarios/_products_modal.html.erb
<div class="modal" data-name="<%= object.name.parameterize %>">
  <div class="modal_content">
    <header class="modal_header">
      <%= content_tag :h4, "Add Products to the #{object.name}" %>
    </header>

    <%= button_tag '✗', class: 'link plain js_modal_toggle', data: { 'name' => object.name.parameterize }  %>
    <ul class="errors"></ul>

    <%= form_tag products_search_path, remote: true, class: 'product_search' do %>
      <%= hidden_field_tag :scenario_name, object.name.parameterize %>
      <%= submit_tag 'search', class: 'btn primary product_submit' %>

      <div class="product_search_wrapper">
        <%= text_field_tag :product, nil, class: 'product_query', placeholder: 'IBM Product Name' %>
      </div>
    <% end %>

    <section class="results_wrapper closed">
      <div class="product_count_wrapper">
        <p>There are <span class="product_count"></span> results that matched your search.</p>
        <button class="link primary product_reset">reset</button>
      </div>

      <div class="results_container"><div class="results"></div></div>

      <button class="link plain modal_scroll top">first</button>
      <button class="link plain modal_scroll bottom">last</button>
    </section>
  </div>
</div>

<div class="modal_overlay"></div>

app/views/scenarios/_scenario.html.erb
<%= div_for scenario, class: 'card', data: { name: scenario.name.parameterize } do %>
  <div class="card_container">
    <%= image_tag scenario.avatar, class: 'scenario_avatar icon' %>
    <%= content_tag :h2, scenario.name %>
    <%= content_tag :h3, scenario.quote %>
    <%= content_tag :p , scenario.pitch %>

    <%= content_tag :section, class: products_container(scenario) do %>
      <%= content_tag :h4, 'Products' %>
      <%= render(scenario.products) || render('shared/empty', object: 'product') %>
    <% end %>
  </div>

  <div class="card_admin">
    <%= link_to 'edit', edit_scenario_path(scenario), remote: true, class: 'link plain' %>
    <%= link_to 'delete', scenario_path(scenario), method: :delete, remote: true, class: 'link delete delete_scenario' %>
    <%= button_tag 'add products', class: 'link primary js_modal_toggle', data: { name: scenario.name.parameterize } %>
  </div>
<% end %>

<%= render 'products/modal', object: scenario %>

app/views/scenarios/create.js.erb
<%= render 'shared/create', object: @scenario %>

app/views/scenarios/destroy.js.erb
<%= render 'shared/destroy', object: @scenario %>

app/views/scenarios/edit.js.erb
<%= render 'shared/edit', resource: 'scenario', object: @scenario %>

app/views/scenarios/new.js.erb
<%= render 'shared/new', resource: 'scenario', object: [@solution, @solution.scenarios.build] %>

app/views/scenarios/update.js.erb
<%= render 'shared/update', object: @scenario %>