config/routes.rb
Rails.application.routes.draw do
  root 'solutions#index'

  resources :solutions, shallow: true do
    member do
      get 'preview'
    end

    resources :scenarios, except: [:index]
    resources :resources, only: [:new, :create, :edit, :update, :destroy]
  end

  #
  # TODO - How else to avoid deeply nested routes without re-generating
  #        these Scenarios resources? Passing an empty array to only
  #        ensures that no new resources are generated as we've already
  #        generated everything we need above (with solutions/scenarios)
  #
  resources :scenarios, only: [] do
    resources :products, only: [:search, :create, :destroy]
  end

  post '/products/search', to: 'products#search', as: :products_search

  devise_for :users
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :scenario
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  respond_to :js

  def create
    @scenario = Scenario.friendly.find(params[:scenario_id])
    @product  = @scenario.products.create(product_params)
    @scenario_name = params[:scenario_id]
  end

  def destroy
    @scenario = Scenario.friendly.find(params[:scenario_id])
    @product  = @scenario.products.find(params[:id])

    @product.destroy
  end

  def search
    @scenario_name = params[:scenario_name]
    @search_query  = params[:product]
    @results       = JSON.generate(ProductAPI.search_products(params[:product]))
  end

  private

  def product_params
    params.permit(:product_id, :name, :description, :icon_url)
  end
end

app/views/products/_empty.html.erb
<div class="empty">
  <p>This scenario has no products!</p>
</div>

app/views/products/_form.html.erb
<%= form_for([@scenario, @product]) do |f| %>
  <%= f.text_field :product_id %>
  <%= f.submit 'add product' %>
<% end %>

app/views/products/_index.html.erb
<div class="product">
  <%= content_tag :strong, object.name %>
  <%= content_tag :p, object.description %>
  <%= link_to 'delete', scenario_product_path(object.scenario_id, object), method: :delete, remote: true, class: 'link delete_product' %>
</div>

app/views/products/_modal.html.erb
<div class="modal" data-name="<%= object.name.parameterize %>">
  <div class="modal_content">
    <header class="modal_header">
      <%= content_tag :h4, "Add Products to the #{object.name}" %>
    </header>

    <%= button_tag '✗', class: 'link plain js_modal_toggle', data: { 'name' => object.name.parameterize }  %>
    <ul class="errors"></ul>

    <%= form_tag products_search_path, remote: true, class: 'product_search' do %>
      <%= hidden_field_tag :scenario_name, object.name.parameterize %>
      <%= submit_tag 'search', class: 'btn primary product_submit' %>

      <div class="product_search_wrapper">
        <%= text_field_tag :product, nil, class: 'product_query', placeholder: 'IBM Product Name' %>
      </div>
    <% end %>

    <section class="results_wrapper closed">
      <div class="product_count_wrapper">
        <p>There are <span class="product_count"></span> results that matched your search.</p>
        <button class="link primary product_reset">reset</button>
      </div>

      <div class="results_container"><div class="results"></div></div>

      <button class="link plain modal_scroll top">first</button>
      <button class="link plain modal_scroll bottom">last</button>
    </section>
  </div>
</div>

<div class="modal_overlay"></div>

app/views/products/_product.html.erb
<%= div_for product do %>
  <%= content_tag :strong, product.name %>
  <%= content_tag :p, product.description %>
  <%= link_to 'delete', scenario_product_path(product.scenario_id, product), method: :delete, remote: true, class: 'link delete delete_product' %>
<% end %>

app/views/products/create.js.erb
<% if @product.errors.any? %>

  <% @product.errors.full_messages.each do |error| %>
    $( '.modal[data-name="<%= @scenario_name %>"] .errors' )
      .append( '<p>' + '<%= message.html_safe %>' + '</p>' );
  <% end %>

<% else %>

  $( '.scenario[data-name="<%= @scenario_name %>"] .products' )
    .append( '<%= j render(@product) %>' )
    .find( '.empty' )
    .remove();

<% end %>

app/views/products/destroy.js.erb
<%# TODO - DRY up this partial and render "shared/destroy" when the helper methods are cleaned up -%>

$('<%= id_selector(@product) %>').remove();

if($('<%= individual_resource_selector(@product) %>').length === 0) {
  $('<%= products_container_class(@product.scenario) %>').append( '<%= j render("shared/empty", object: plural_resource_name(@product)) %>' );
}

app/views/products/search.js.erb
// Ensure only the current modal is targeted
var results  = <%= raw json_escape(@results) %>
,   $modal   = $('.modal[data-name=<%= @scenario_name %>]')
,   $errors  = $modal.find('.errors')
,   $search  = $modal.find('.product_query')
,   $count   = $modal.find('.product_count')
,   $results = $modal.find('.results_wrapper')
,   $submit  = $modal.find('.product_submit');

// Search is complete, update the UI
$submit.removeClass('loading');

// Do we have any results?
if(results.length === 0) {

  $errors.append('<li>Your search did not return any resesults.</li>').slideDown();

}
else {

  // Toggle visibility of the results wrapper
  $results.toggleClass('open closed');

  // Update the UI with the total number of results
  $count.html(results.length);

  // Iterate over results and append each to the DOM
  results.forEach(function(result) {

    $results
      .find('.results').append(
        '<article class="product result unsaved" data-id="' + result["id"] + '">'
        + '<p class="product_name">' + result["name"] + '</p>'
        + '<p class="product_description">' + result["product_name"] + '</p>'
      + '</article>'
      )
      .parent().scrollTop(0);

  });

};

// Delegate event when user interacts with any result
$('.results').on('click', '.result.unsaved', function() {

  // Cache reference to the current jQuery object
  $this = $(this);

  // Stash product id
  var id = $this.data('id');

  // Get current scenario id
  var scenario_name = $this.parents('.modal').data('name');

  // Build destination for POST for /scenarios/:scenario_friendly_id/products
  var post_url = '/scenarios/' + scenario_name + '/products';

  // Save product via AJAX POST request
  $.ajax({
    type: 'POST',
    url:  post_url,
    data: results[id]
  }).done(function() {
    $this
      .toggleClass('saved unsaved')
      .append('<span class="ui-check">✔︎</span>');
  });

});