config/routes.rb
Rails.application.routes.draw do
  root 'solutions#index'

  resources :solutions, shallow: true do
    member do
      get 'preview'
    end

    resources :scenarios, except: [:index]
    resources :resources, only: [:new, :create, :edit, :update, :destroy]
  end

  #
  # TODO - How else to avoid deeply nested routes without re-generating
  #        these Scenarios resources? Passing an empty array to only
  #        ensures that no new resources are generated as we've already
  #        generated everything we need above (with solutions/scenarios)
  #
  resources :scenarios, only: [] do
    resources :products, only: [:search, :create, :destroy]
  end

  post '/products/search', to: 'products#search', as: :products_search

  devise_for :users
end

app/models/solution.rb
class Solution < ActiveRecord::Base
  extend FriendlyId

  has_many :scenarios, dependent: :destroy
  has_many :resources, dependent: :destroy

  validates_presence_of :name

  # Use :name field as slug for ID
  friendly_id :name, use: :slugged

  # Paperclip file configuration
  has_attached_file :header,
                    :styles => { :default => '1900x300' },
                    :default_url => '/assets/images/defaults/header.jpg'

  # Paperclip validation helper method to ensure header image type is valid
  validates_attachment_content_type :header, :content_type => /\Aimage\/.*\Z/

  # Require all fields if the user attempts to publish the solution
  with_options if: :published? do |solution|
    solution.validates :header, presence: true
    solution.validates :title,  presence: true
    solution.validates :body,   presence: true
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  respond_to :html, :js

  before_action :authenticate_user!, except: [:preview]
  before_action :set_solution, only: [:show, :preview, :edit, :update, :destroy]

  def index
    @solutions = Solution.all
  end

  def new
    @solution = Solution.new
  end

  def create
    @solution = Solution.create(solution_params)
  end

  def edit
  end

  def show
  end

  def update
    @solution.update(solution_params)
  end

  def destroy
    @solution.destroy
  end

  def preview
    # TODO - This creeped in from a feature prototype; it needs refactoring
    solution  = @solution
    resources = solution.resources
    scenarios = solution.scenarios
    products  = []

    scenarios.each do |scenario|
      scenario.products.each do |product|
        products << product
      end
    end

    data = {
      'solution'  => solution,
      'resources' => resources,
      'scenarios' => scenarios,
      'products'  => products,
    }

    respond_to do |format|
      format.html { render layout: 'preview' }
      format.json { render json: data }
    end
  end

  private

  def solution_params
    params[:solution].permit(:name, :title, :body, :header, :published)
  end

  def set_solution
    @solution = Solution.friendly.find(params[:id])
  end
end

app/views/solutions/_form.html.erb
<%= form_for object, html: { multipart: true }, remote: true do |f| %>
  <div class="<%= container_class %>">
    <ul class="errors"></ul>

    <% if edit? %>
      <%= image_tag object.header, class: 'solution_header' %>
    <% end %>

    <%= f.label :name, 'Solution Name' %>
    <%= f.text_field :name, class: 'instance_name' %>

    <%= f.label :title, 'Leadspace Copy' %>
    <%= f.text_field :title %>

    <%= f.label :body, 'Body Copy' %>
    <%= f.text_area :body %>

    <%= f.label :header, 'Leadspace Image' %>
    <%= f.file_field :header %>
  </div>

  <% if new? %>
    <%= f.submit 'save', class: 'btn primary', id: 'save_solution' %>
  <% elsif edit? %>
    <div class="card_admin">
      <%= f.submit 'save', class: 'link primary', id: 'save_solution' %>
    </div>
  <% end %>
<% end %>

app/views/solutions/_solution.html.erb
<%= div_for solution, class: 'card' do %>
  <div class="card_container">
    <%= image_tag solution.header, class: 'solution_header' %>
    <%= content_tag :h2, solution.name %>
    <%= content_tag :p, solution.title, class: 'section_header' %>
    <%= content_tag :p, solution.body %>
  </div>

  <div class="card_admin">
    <% if action_name == 'index' || action_name == 'create' %>
      <%= link_to 'view', solution_path(solution), class: 'link' %>
      <%= link_to 'delete', solution_path(solution), method: :delete, remote: true, class: 'link delete' %>
    <% elsif action_name == 'show' %>
      <%= link_to 'edit', edit_solution_path(solution), remote: true, class: 'link plain' %>
    <% end %>
  </div>
<% end %>

app/views/solutions/create.js.erb
<%= render 'shared/create', object: @solution %>

app/views/solutions/destroy.js.erb
<%= render 'shared/destroy', object: @solution %>

app/views/solutions/edit.js.erb
<%= render 'shared/edit', resource: 'solution', object: @solution %>

app/views/solutions/index.html.erb
<% content_for :sub_header do %>
  <h1>Solutions Pages</h1>
<% end %>

<div class="solutions solutions">
  <%= render 'shared/collection_header', object: 'solution', parent_object: nil %>
  <%= render(@solutions) || render('shared/empty', object: 'solutions') %>
</div>

app/views/solutions/new.js.erb
<%= render 'shared/new', resource: 'solution', object: @solution %>

app/views/solutions/show.html.erb
<% content_for :sub_header do %>
  <%= content_tag :h1, "Solution Page" %>
<% end %>

<section class="solutions collection">
  <%= render @solution %>
</section>

<section class="scenarios collection">
  <%= render 'shared/collection_header', object: 'scenario', parent_object: @solution %>
  <%= render(@solution.scenarios) || render('shared/empty', object: 'scenarios') %>
</section>

<div class="resources collection">
  <%= render 'shared/collection_header', object: 'resource', parent_object: @solution %>
  <%= render(@solution.resources) || render('shared/empty', object: 'resources') %>
</div>

app/views/solutions/update.js.erb
<%= render 'shared/update', object: @solution %>